# Generated by Django 4.1.7 on 2023-09-28 22:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteAeroportuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodAgente', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Agentes Aeroportuarios',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'Este correo electrónico ya está en uso.'}, max_length=100, unique=True)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('numeroDocumento', models.CharField(error_messages={'unique': 'Este DNI ya está en uso.'}, max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('primerNombre', models.CharField(max_length=100)),
                ('segundoNombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_users', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cargo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='TipoDePapeleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Papeletas',
            },
        ),
        migrations.CreateModel(
            name='TipoDeSancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Sanciones',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Empleados',
            },
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empleado')),
                ('tipoSancion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodesancion')),
            ],
            options={
                'verbose_name_plural': 'Sanciones',
            },
        ),
        migrations.CreateModel(
            name='Papeleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=20)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('AgenteA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agenteaeroportuario')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empleado')),
                ('tipoPapeleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodepapeleta')),
            ],
            options={
                'verbose_name_plural': 'Papeletas',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipoEmpleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoempleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customuser'),
        ),
        migrations.CreateModel(
            name='Descargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empleado')),
                ('papeleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.papeleta')),
            ],
            options={
                'verbose_name_plural': 'Descargos',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipoDocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodocumento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='agenteaeroportuario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customuser'),
        ),
    ]
